name: oag_camera
description: A new Flutter package project.
version: 0.0.1
homepage:
#signal9966
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

  # Camera
  camera: ^0.10.5+4
  flutter_image_compress: ^2.0.4

  # Code generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.6.0

  # State management
  flutter_bloc: ^8.1.3

  # Utility
  auto_size_text: ^3.0.0
  collection: ^1.17.2
  equatable: ^2.0.5
  oag_snack_bar:
    git:
      url: https://github.com/birkineau/oag_snack_bar
  path: ^1.8.3
  path_provider: ^2.0.14
  geolocator: ^10.0.1

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner:
  freezed:
  json_serializable:

flutter:
  generate: false
  uses-material-design: true

  # assets:
  #   - lib/assets/images/camera_status_not_ready.png
